apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: {{ .Values.namespace }}
data:
  litellm.yaml: |
    model_list:
    {{- toYaml .Values.proxyConfig.model_list | nindent 4 }}