{{- if .Values.gcp.serviceAccountKey }}
apiVersion: v1
kind: Secret
metadata:
  name: gcp-service-account-key
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  gcp-key.json: {{ .Values.gcp.serviceAccountKey | b64enc }}
{{- end }}
